name: Deploy Node.js and React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Укажите версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build --if-present

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          server-dir: /httpdocs # Укажите директорию на вашем сервере
